version: "3.8"

services:

  web-app:
    image: yankoaboutmecr.azurecr.io/about_me:1
    container_name: my-portfolio
    build:
      dockerfile: Dockerfile
    ports:
      - "80:80"
    domainname: "about-me"
