version: "3.8"

services:

  web-app:
    image: yankoaboutmecr.azurecr.io/about_me:1
    container_name: my-portfolio-yanko
    build:
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    domainname: "about-me"
