name: Schedule for GET requests

on:
  schedule:
    - cron: '*/10 * * * *'
  workflow_dispatch:

jobs:
  keep-it-alive:
    runs-on: ubuntu-latest
    steps:
      - name: Keep WebApp alive
        run: |
          for i in {1..3}
          do
            echo "Execute first GET requests"
            response=$(curl -sS https://yr-portoflio.onrender.com/)
            echo "Wait 5 seconds"
            sleep 5
            echo "Execute second GET requests"
            response=$(curl -sS https://yr-portoflio.onrender.com/#skills)
            echo "Wait 5 seconds"
            sleep 5
            echo "Execute third GET requests"
            response=$(curl -sS https://yr-portoflio.onrender.com/get?message=Hi)
            echo "Wait 5 seconds"
            sleep 5
            echo "Execute fourth GET requests"
            response=$(curl -sS https://yr-portoflio.onrender.com/get?message=Hello)
            echo "Wait 5 seconds"
            sleep 5
            echo "GET Request operation was successful"
          done

      - name: Remove scheduled job
        uses: cardinalby/unschedule-job-action@v1
        with:
          ghToken: ${{ secrets.MY_TOKEN }}
