name: Schedule for GET requests

on:
  schedule:
    - cron: '*/10 * * * *'
  workflow_dispatch:

jobs:
  Keep-It-Alive:
    runs-on: ubuntu-latest
    steps:
      - name: Keep WebApp alive
        run: |
          for i in {1..2}
          do
            echo "Execute first GET requests"
            response=$(curl -sS https://yr-portoflio.onrender.com/)
            echo "Wait 3 seconds"
            sleep 3
            echo "Execute second GET requests"
            response=$(curl -sS https://yr-portoflio.onrender.com/#skills)
            echo "Wait 6 seconds"
            sleep 6
            echo "Execute third GET requests"
            response=$(curl -sS "https://yr-portoflio.onrender.com/get?message=Hi%20how%20are%20you?")
            echo "Wait 4 seconds"
            sleep 4
            echo "Execute fourth GET requests"
            response=$(curl -sS "https://yr-portoflio.onrender.com/get?message=Tell%20me%20about%20tech%20stack?")
            echo "Wait 5 seconds"
            sleep 5
            echo "GET Request operation was successful"
          done

      - name: Delete old scheduled workflow runs
        uses: MajorScruffy/delete-old-workflow-runs@v0.3.0
        with:
          repository: ${{ github.repository }}
          workflow: ".github/workflows/keep_it_alive.yml"
          older-than-seconds: 3600
          event: schedule
        env:
          GITHUB_TOKEN: ${{ secrets.MY_TOKEN }}