name: Schedule for GET requests

on:
  schedule:
    - cron: '*/14 * * * *'

jobs:
  keep-it-alive-cron:
    runs-on: ubuntu-latest
    steps:
      - name: Keep WebApp alive
        run: |
          while true
          do
            echo "Execute first GET requests"
            curl https://yr-portoflio.onrender.com/ -o /dev/null
            echo "Wait 5 seconds"
            sleep 5
            echo "Execute second GET requests"
            curl https://yr-portoflio.onrender.com/#skills -o /dev/null
            echo "Wait 5 seconds"
            sleep 5
            echo "Execute third GET requests"
            curl https://yr-portoflio.onrender.com/#contact -o /dev/null
            echo "Wait 5 seconds"
            sleep 5
            echo "Execute fourth GET requests"
            curl https://yr-portoflio.onrender.com/#certificates -o /dev/null
            echo "GET Request operation was successful"
            break
          done
