name: Schedule for GET requests

on:
  schedule:
    - cron: '*/10 * * * *'

jobs:
  keep-it-alive:
    runs-on: ubuntu-latest
    steps:
      - name: Keep WebApp alive
        run: |
          for i in {1..3}
          do
            echo "Execute first GET requests"
            curl https://yr-portoflio.onrender.com/ 
            echo "Wait 5 seconds"
            sleep 5
            echo "Execute second GET requests"
            curl https://yr-portoflio.onrender.com/#skills 
            echo "Wait 5 seconds"
            sleep 5
            echo "Execute third GET requests"
            curl https://yr-portoflio.onrender.com/#contact
            echo "Wait 5 seconds"
            sleep 5
            echo "Execute fourth GET requests"
            curl https://yr-portoflio.onrender.com/#certificates
            echo "Wait 5 seconds"
            sleep 5
            echo "GET Request operation was successful"
          done
