name: Schedule for GET requests

on:
  schedule:
    - cron: '*/10 * * * *'
  workflow_dispatch:

jobs:
  keep-it-alive:
    runs-on: ubuntu-latest
    steps:
      - name: Keep WebApp alive
        run: |
          for i in {1..2}
          do
            echo "Execute first GET requests"
            response=$(curl -sS https://yr-portoflio.onrender.com/)
            echo "Wait 5 seconds"
            sleep 5
            echo "Execute second GET requests"
            response=$(curl -sS https://yr-portoflio.onrender.com/#skills)
            echo "Wait 5 seconds"
            sleep 5
            echo "Execute third GET requests"
            response=$(curl -sS https://yr-portoflio.onrender.com/get?message="Hi, how are you?")
            echo "Wait 5 seconds"
            sleep 5
            echo "Execute fourth GET requests"
            response=$(curl -sS https://yr-portoflio.onrender.com/get?message="Tell me about tech stack?")
            echo "Wait 5 seconds"
            sleep 5
            echo "GET Request operation was successful"
          done

      - name: Delete old scheduled workflow runs
        uses: MajorScruffy/delete-old-workflow-runs@v0.3.0
        with:
          repository: ${{ github.repository }}
          workflow: ".github/workflows/keep_it_alive.yml"
          older-than-seconds: 3600
          event: schedule
        env:
          GITHUB_TOKEN: ${{ secrets.MY_TOKEN }}